# Generated by Django 3.1 on 2021-01-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='images/default_cover.jpg', upload_to='images/cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images/profile'),
        ),
    ]
