# Generated by Django 3.1 on 2021-01-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210122_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='images/default_cover.jpg', upload_to='images/cover'),
        ),
    ]
